/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as UpsellRouteImport } from './routes/upsell'
import { Route as SemAcessoRouteImport } from './routes/sem-acesso'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as DownsellRouteImport } from './routes/downsell'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as ApiDriveIdRouteImport } from './routes/api/drive.$id'
import { Route as AuthenticatedReadIdRouteImport } from './routes/_authenticated/read.$id'
import { Route as AuthenticatedCollectionSlugRouteImport } from './routes/_authenticated/collection.$slug'
import { Route as AuthenticatedCategorySlugRouteImport } from './routes/_authenticated/category.$slug'
import { Route as AuthenticatedBookIdRouteImport } from './routes/_authenticated/book.$id'
import { Route as ApiPublicWebhooksWiapayRouteImport } from './routes/api/public/webhooks/wiapay'
import { Route as ApiPublicWebhooksKiwifyRouteImport } from './routes/api/public/webhooks/kiwify'
import { Route as ApiPublicWebhooksHotmartRouteImport } from './routes/api/public/webhooks/hotmart'
import { Route as ApiPublicWebhooksCaktoRouteImport } from './routes/api/public/webhooks/cakto'
import { Route as ApiDriveIdEpubRouteImport } from './routes/api/drive.$id.epub'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const SemAcessoRoute = SemAcessoRouteImport.update({
  id: '/sem-acesso',
  path: '/sem-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const DownsellRoute = DownsellRouteImport.update({
  id: '/downsell',
  path: '/downsell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDriveIdRoute = ApiDriveIdRouteImport.update({
  id: '/api/drive/$id',
  path: '/api/drive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReadIdRoute = AuthenticatedReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionSlugRoute =
  AuthenticatedCollectionSlugRouteImport.update({
    id: '/collection/$slug',
    path: '/collection/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategorySlugRoute =
  AuthenticatedCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookIdRoute = AuthenticatedBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksWiapayRoute = ApiPublicWebhooksWiapayRouteImport.update({
  id: '/api/public/webhooks/wiapay',
  path: '/api/public/webhooks/wiapay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksKiwifyRoute = ApiPublicWebhooksKiwifyRouteImport.update({
  id: '/api/public/webhooks/kiwify',
  path: '/api/public/webhooks/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksHotmartRoute =
  ApiPublicWebhooksHotmartRouteImport.update({
    id: '/api/public/webhooks/hotmart',
    path: '/api/public/webhooks/hotmart',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksCaktoRoute = ApiPublicWebhooksCaktoRouteImport.update({
  id: '/api/public/webhooks/cakto',
  path: '/api/public/webhooks/cakto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveIdEpubRoute = ApiDriveIdEpubRouteImport.update({
  id: '/epub',
  path: '/epub',
  getParentRoute: () => ApiDriveIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downsell': typeof DownsellRoute
  '/obrigado': typeof ObrigadoRoute
  '/quiz': typeof QuizRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/upsell': typeof UpsellRoute
  '/vendas': typeof VendasRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/book/$id': typeof AuthenticatedBookIdRoute
  '/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/collection/$slug': typeof AuthenticatedCollectionSlugRoute
  '/read/$id': typeof AuthenticatedReadIdRoute
  '/api/drive/$id': typeof ApiDriveIdRouteWithChildren
  '/api/drive/$id/epub': typeof ApiDriveIdEpubRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/hotmart': typeof ApiPublicWebhooksHotmartRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
  '/api/public/webhooks/wiapay': typeof ApiPublicWebhooksWiapayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downsell': typeof DownsellRoute
  '/obrigado': typeof ObrigadoRoute
  '/quiz': typeof QuizRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/upsell': typeof UpsellRoute
  '/vendas': typeof VendasRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/book/$id': typeof AuthenticatedBookIdRoute
  '/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/collection/$slug': typeof AuthenticatedCollectionSlugRoute
  '/read/$id': typeof AuthenticatedReadIdRoute
  '/api/drive/$id': typeof ApiDriveIdRouteWithChildren
  '/api/drive/$id/epub': typeof ApiDriveIdEpubRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/hotmart': typeof ApiPublicWebhooksHotmartRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
  '/api/public/webhooks/wiapay': typeof ApiPublicWebhooksWiapayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/downsell': typeof DownsellRoute
  '/obrigado': typeof ObrigadoRoute
  '/quiz': typeof QuizRoute
  '/sem-acesso': typeof SemAcessoRoute
  '/upsell': typeof UpsellRoute
  '/vendas': typeof VendasRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/book/$id': typeof AuthenticatedBookIdRoute
  '/_authenticated/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/_authenticated/collection/$slug': typeof AuthenticatedCollectionSlugRoute
  '/_authenticated/read/$id': typeof AuthenticatedReadIdRoute
  '/api/drive/$id': typeof ApiDriveIdRouteWithChildren
  '/api/drive/$id/epub': typeof ApiDriveIdEpubRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/hotmart': typeof ApiPublicWebhooksHotmartRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
  '/api/public/webhooks/wiapay': typeof ApiPublicWebhooksWiapayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/downsell'
    | '/obrigado'
    | '/quiz'
    | '/sem-acesso'
    | '/upsell'
    | '/vendas'
    | '/categories'
    | '/favorites'
    | '/library'
    | '/profile'
    | '/book/$id'
    | '/category/$slug'
    | '/collection/$slug'
    | '/read/$id'
    | '/api/drive/$id'
    | '/api/drive/$id/epub'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/hotmart'
    | '/api/public/webhooks/kiwify'
    | '/api/public/webhooks/wiapay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/downsell'
    | '/obrigado'
    | '/quiz'
    | '/sem-acesso'
    | '/upsell'
    | '/vendas'
    | '/categories'
    | '/favorites'
    | '/library'
    | '/profile'
    | '/book/$id'
    | '/category/$slug'
    | '/collection/$slug'
    | '/read/$id'
    | '/api/drive/$id'
    | '/api/drive/$id/epub'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/hotmart'
    | '/api/public/webhooks/kiwify'
    | '/api/public/webhooks/wiapay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/downsell'
    | '/obrigado'
    | '/quiz'
    | '/sem-acesso'
    | '/upsell'
    | '/vendas'
    | '/_authenticated/categories'
    | '/_authenticated/favorites'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/_authenticated/book/$id'
    | '/_authenticated/category/$slug'
    | '/_authenticated/collection/$slug'
    | '/_authenticated/read/$id'
    | '/api/drive/$id'
    | '/api/drive/$id/epub'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/hotmart'
    | '/api/public/webhooks/kiwify'
    | '/api/public/webhooks/wiapay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DownsellRoute: typeof DownsellRoute
  ObrigadoRoute: typeof ObrigadoRoute
  QuizRoute: typeof QuizRoute
  SemAcessoRoute: typeof SemAcessoRoute
  UpsellRoute: typeof UpsellRoute
  VendasRoute: typeof VendasRoute
  ApiDriveIdRoute: typeof ApiDriveIdRouteWithChildren
  ApiPublicWebhooksCaktoRoute: typeof ApiPublicWebhooksCaktoRoute
  ApiPublicWebhooksHotmartRoute: typeof ApiPublicWebhooksHotmartRoute
  ApiPublicWebhooksKiwifyRoute: typeof ApiPublicWebhooksKiwifyRoute
  ApiPublicWebhooksWiapayRoute: typeof ApiPublicWebhooksWiapayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sem-acesso': {
      id: '/sem-acesso'
      path: '/sem-acesso'
      fullPath: '/sem-acesso'
      preLoaderRoute: typeof SemAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downsell': {
      id: '/downsell'
      path: '/downsell'
      fullPath: '/downsell'
      preLoaderRoute: typeof DownsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/drive/$id': {
      id: '/api/drive/$id'
      path: '/api/drive/$id'
      fullPath: '/api/drive/$id'
      preLoaderRoute: typeof ApiDriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/read/$id': {
      id: '/_authenticated/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof AuthenticatedReadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collection/$slug': {
      id: '/_authenticated/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof AuthenticatedCollectionSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/category/$slug': {
      id: '/_authenticated/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof AuthenticatedCategorySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$id': {
      id: '/_authenticated/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof AuthenticatedBookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/wiapay': {
      id: '/api/public/webhooks/wiapay'
      path: '/api/public/webhooks/wiapay'
      fullPath: '/api/public/webhooks/wiapay'
      preLoaderRoute: typeof ApiPublicWebhooksWiapayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/kiwify': {
      id: '/api/public/webhooks/kiwify'
      path: '/api/public/webhooks/kiwify'
      fullPath: '/api/public/webhooks/kiwify'
      preLoaderRoute: typeof ApiPublicWebhooksKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/hotmart': {
      id: '/api/public/webhooks/hotmart'
      path: '/api/public/webhooks/hotmart'
      fullPath: '/api/public/webhooks/hotmart'
      preLoaderRoute: typeof ApiPublicWebhooksHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/cakto': {
      id: '/api/public/webhooks/cakto'
      path: '/api/public/webhooks/cakto'
      fullPath: '/api/public/webhooks/cakto'
      preLoaderRoute: typeof ApiPublicWebhooksCaktoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/$id/epub': {
      id: '/api/drive/$id/epub'
      path: '/epub'
      fullPath: '/api/drive/$id/epub'
      preLoaderRoute: typeof ApiDriveIdEpubRouteImport
      parentRoute: typeof ApiDriveIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedBookIdRoute: typeof AuthenticatedBookIdRoute
  AuthenticatedCategorySlugRoute: typeof AuthenticatedCategorySlugRoute
  AuthenticatedCollectionSlugRoute: typeof AuthenticatedCollectionSlugRoute
  AuthenticatedReadIdRoute: typeof AuthenticatedReadIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedBookIdRoute: AuthenticatedBookIdRoute,
  AuthenticatedCategorySlugRoute: AuthenticatedCategorySlugRoute,
  AuthenticatedCollectionSlugRoute: AuthenticatedCollectionSlugRoute,
  AuthenticatedReadIdRoute: AuthenticatedReadIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiDriveIdRouteChildren {
  ApiDriveIdEpubRoute: typeof ApiDriveIdEpubRoute
}

const ApiDriveIdRouteChildren: ApiDriveIdRouteChildren = {
  ApiDriveIdEpubRoute: ApiDriveIdEpubRoute,
}

const ApiDriveIdRouteWithChildren = ApiDriveIdRoute._addFileChildren(
  ApiDriveIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DownsellRoute: DownsellRoute,
  ObrigadoRoute: ObrigadoRoute,
  QuizRoute: QuizRoute,
  SemAcessoRoute: SemAcessoRoute,
  UpsellRoute: UpsellRoute,
  VendasRoute: VendasRoute,
  ApiDriveIdRoute: ApiDriveIdRouteWithChildren,
  ApiPublicWebhooksCaktoRoute: ApiPublicWebhooksCaktoRoute,
  ApiPublicWebhooksHotmartRoute: ApiPublicWebhooksHotmartRoute,
  ApiPublicWebhooksKiwifyRoute: ApiPublicWebhooksKiwifyRoute,
  ApiPublicWebhooksWiapayRoute: ApiPublicWebhooksWiapayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
