/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpsellRouteImport } from './routes/upsell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DownsellRouteImport } from './routes/downsell'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadIdRouteImport } from './routes/read.$id'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as ApiDriveIdRouteImport } from './routes/api/drive.$id'
import { Route as ApiDriveIdEpubRouteImport } from './routes/api/drive.$id.epub'

const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DownsellRoute = DownsellRouteImport.update({
  id: '/downsell',
  path: '/downsell',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveIdRoute = ApiDriveIdRouteImport.update({
  id: '/api/drive/$id',
  path: '/api/drive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveIdEpubRoute = ApiDriveIdEpubRouteImport.update({
  id: '/epub',
  path: '/epub',
  getParentRoute: () => ApiDriveIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/downsell': typeof DownsellRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/upsell': typeof UpsellRoute
  '/book/$id': typeof BookIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/read/$id': typeof ReadIdRoute
  '/api/drive/$id': typeof ApiDriveIdRouteWithChildren
  '/api/drive/$id/epub': typeof ApiDriveIdEpubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/downsell': typeof DownsellRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/upsell': typeof UpsellRoute
  '/book/$id': typeof BookIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/read/$id': typeof ReadIdRoute
  '/api/drive/$id': typeof ApiDriveIdRouteWithChildren
  '/api/drive/$id/epub': typeof ApiDriveIdEpubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/downsell': typeof DownsellRoute
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/upsell': typeof UpsellRoute
  '/book/$id': typeof BookIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/read/$id': typeof ReadIdRoute
  '/api/drive/$id': typeof ApiDriveIdRouteWithChildren
  '/api/drive/$id/epub': typeof ApiDriveIdEpubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/downsell'
    | '/favorites'
    | '/library'
    | '/profile'
    | '/upsell'
    | '/book/$id'
    | '/category/$slug'
    | '/collection/$slug'
    | '/read/$id'
    | '/api/drive/$id'
    | '/api/drive/$id/epub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/downsell'
    | '/favorites'
    | '/library'
    | '/profile'
    | '/upsell'
    | '/book/$id'
    | '/category/$slug'
    | '/collection/$slug'
    | '/read/$id'
    | '/api/drive/$id'
    | '/api/drive/$id/epub'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/downsell'
    | '/favorites'
    | '/library'
    | '/profile'
    | '/upsell'
    | '/book/$id'
    | '/category/$slug'
    | '/collection/$slug'
    | '/read/$id'
    | '/api/drive/$id'
    | '/api/drive/$id/epub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  DownsellRoute: typeof DownsellRoute
  FavoritesRoute: typeof FavoritesRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  UpsellRoute: typeof UpsellRoute
  BookIdRoute: typeof BookIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  ReadIdRoute: typeof ReadIdRoute
  ApiDriveIdRoute: typeof ApiDriveIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downsell': {
      id: '/downsell'
      path: '/downsell'
      fullPath: '/downsell'
      preLoaderRoute: typeof DownsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/$id': {
      id: '/api/drive/$id'
      path: '/api/drive/$id'
      fullPath: '/api/drive/$id'
      preLoaderRoute: typeof ApiDriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/$id/epub': {
      id: '/api/drive/$id/epub'
      path: '/epub'
      fullPath: '/api/drive/$id/epub'
      preLoaderRoute: typeof ApiDriveIdEpubRouteImport
      parentRoute: typeof ApiDriveIdRoute
    }
  }
}

interface ApiDriveIdRouteChildren {
  ApiDriveIdEpubRoute: typeof ApiDriveIdEpubRoute
}

const ApiDriveIdRouteChildren: ApiDriveIdRouteChildren = {
  ApiDriveIdEpubRoute: ApiDriveIdEpubRoute,
}

const ApiDriveIdRouteWithChildren = ApiDriveIdRoute._addFileChildren(
  ApiDriveIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  DownsellRoute: DownsellRoute,
  FavoritesRoute: FavoritesRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  UpsellRoute: UpsellRoute,
  BookIdRoute: BookIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  ReadIdRoute: ReadIdRoute,
  ApiDriveIdRoute: ApiDriveIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
